name: Build Docker Image
on:
  push:
    paths:
      - 'Dockerfile'
      - '.github/workflows/build.yml'
  schedule:
    - cron: '0 0 * * 0'

env:
    IMAGE_NAME: ptr-test
    IMAGE_TAGS: v1 ${{ github.sha }}
    IMAGE_REGISTRY: ghcr.io/${{ github.repository_owner }}
    REGISTRY_USER: ${{ github.actor }}
    REGISTRY_PASSWORD: ${{ github.token }}

jobs:
  push-ghcr:
    name: Build and push image
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "GitHub Event name: ${{ github.event_name }}"
          # We run this every week and skip building when no update from the spark package
          if [ "${{ github.event_name }}" != "push" ]; then
            git clone --depth 1 https://aur.archlinux.org/com.qq.weixin.spark.git
            cd com.qq.weixin.spark
            current_timestamp=$(git log -1 --format=%ct)
            seven_days_ago=$(date -d "7 days ago" +%s)
            if [ "$current_timestamp" -gt "$seven_days_ago" ]; then
              exit 1
            fi
          fi
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: spark-wechat
          tags: latest
          containerfiles: |
            ./Dockerfile
          build-args: |
            --squash

      - name: Push To GHCR
        uses: ./
        id: push
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: ${{ steps.build_image.outputs.tags }}
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ env.REGISTRY_USER }}
          password: ${{ env.REGISTRY_PASSWORD }}
