name: Build Docker Image
on:
  push:
    branches:
      - 'main'
  schedule:
    - cron: '0 0 * * 0'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        run: |
          echo "GitHub Event name: ${{ github.event_name }}"
          # We run this every week and skip building when no update from the spark package
          if [ "${{ github.event_name }}" != "push" ]; then
            git clone --depth 1 https://aur.archlinux.org/com.qq.weixin.spark.git
            cd com.qq.weixin.spark
            current_timestamp=$(git log -1 --format=%ct)
            seven_days_ago=$(date -d "7 days ago" +%s)
            if [ "$current_timestamp" -gt "$seven_days_ago" ]; then
              exit 1
            fi
          fi
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: wechat-spark:${{ github.run_number }} 
